-- Seed file cleared for production
-- No sample data - ready for production use
--
-- This file was previously used for development sample data
-- All sample data has been removed for production deployment
--
-- To add production seed data (if needed), add it here
-- Examples: essential master data, default roles, system configurations

-- Example of adding essential system roles (uncomment if needed):
-- INSERT INTO roles (name, description) VALUES
--   ('super_admin', 'System super administrator'),
--   ('admin', 'Administrator'),
--   ('doctor', 'Medical professional'),
--   ('nurse', 'Nursing staff'),
--   ('receptionist', 'Front desk staff'),
--   ('technician', 'Medical technician')
-- ON CONFLICT (name) DO NOTHING;