"use client"

import * as React from "react"
import { PrintLayout, PrintSection, PrintRow, PrintCol, PrintField, PrintSignature } from "./print-layout"
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog"

interface RevenuePrintProps {
  revenue: {
    id: string
    report_period: string
    date_from: string
    date_to: string
    total_revenue: number
    total_expenses?: number
    net_profit?: number
    department_breakdown?: Array<{
      department: string
      revenue: number
      percentage: number
    }>
    payment_methods?: Array<{
      method: string
      amount: number
      count: number
    }>
    services_breakdown?: Array<{
      service: string
      count: number
      revenue: number
    }>
    notes?: string
    generated_by?: string
  }
  children: React.ReactNode
}

export function RevenuePrint({ revenue, children }: RevenuePrintProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    })
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      minimumFractionDigits: 2
    }).format(amount)
  }

  // Sample data if none provided
  const defaultDepartments = [
    { department: 'Consultation', revenue: 150000, percentage: 45 },
    { department: 'Surgery', revenue: 100000, percentage: 30 },
    { department: 'Pharmacy', revenue: 50000, percentage: 15 },
    { department: 'Diagnostics', revenue: 33333, percentage: 10 }
  ]

  const defaultPaymentMethods = [
    { method: 'Cash', amount: 200000, count: 150 },
    { method: 'Card', amount: 100000, count: 75 },
    { method: 'UPI', amount: 33333, count: 50 }
  ]

  const departments = revenue.department_breakdown || defaultDepartments
  const paymentMethods = revenue.payment_methods || defaultPaymentMethods
  const totalRevenue = revenue.total_revenue || departments.reduce((sum, dept) => sum + dept.revenue, 0)

  return (
    <Dialog>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <PrintLayout
          documentType="Financial Report"
          documentTitle="Revenue & Financial Analysis Report"
        >
          {/* Report Header Information */}
          <PrintSection title="Report Information">
            <PrintRow>
              <PrintCol>
                <PrintField label="Report ID" value={revenue.id} />
                <PrintField label="Report Period" value={revenue.report_period || 'CURRENT PERIOD'} />
                <PrintField label="Date Range" value={`${formatDate(revenue.date_from)} to ${formatDate(revenue.date_to)}`} />
              </PrintCol>
              <PrintCol>
                <PrintField label="Generated On" value={formatDate(new Date().toISOString())} />
                <PrintField label="Generated By" value={revenue.generated_by || 'Finance Department'} />
                <PrintField label="Report Type" value="Revenue Analysis" />
              </PrintCol>
            </PrintRow>
          </PrintSection>

          {/* Executive Summary */}
          <PrintSection title="Executive Summary">
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              marginBottom: '20pt',
              gap: '15pt'
            }}>
              <div style={{
                flex: 1,
                textAlign: 'center',
                padding: '20pt',
                border: '3px solid #28a745',
                backgroundColor: '#f8fff9',
                borderRadius: '8pt'
              }}>
                <div style={{
                  fontSize: '16pt',
                  fontWeight: 'bold',
                  color: '#28a745',
                  marginBottom: '8pt',
                  textTransform: 'uppercase'
                }}>Total Revenue</div>
                <div style={{
                  fontSize: '24pt',
                  fontWeight: 'bold',
                  color: '#000'
                }}>
                  {formatCurrency(totalRevenue)}
                </div>
              </div>

              {revenue.total_expenses && (
                <div style={{
                  flex: 1,
                  textAlign: 'center',
                  padding: '20pt',
                  border: '3px solid #dc3545',
                  backgroundColor: '#fff8f8',
                  borderRadius: '8pt'
                }}>
                  <div style={{
                    fontSize: '16pt',
                    fontWeight: 'bold',
                    color: '#dc3545',
                    marginBottom: '8pt',
                    textTransform: 'uppercase'
                  }}>Total Expenses</div>
                  <div style={{
                    fontSize: '24pt',
                    fontWeight: 'bold',
                    color: '#000'
                  }}>
                    {formatCurrency(revenue.total_expenses)}
                  </div>
                </div>
              )}

              {revenue.net_profit && (
                <div style={{
                  flex: 1,
                  textAlign: 'center',
                  padding: '20pt',
                  border: '3px solid #007bff',
                  backgroundColor: '#f8f9ff',
                  borderRadius: '8pt'
                }}>
                  <div style={{
                    fontSize: '16pt',
                    fontWeight: 'bold',
                    color: '#007bff',
                    marginBottom: '8pt',
                    textTransform: 'uppercase'
                  }}>Net Profit</div>
                  <div style={{
                    fontSize: '24pt',
                    fontWeight: 'bold',
                    color: '#000'
                  }}>
                    {formatCurrency(revenue.net_profit)}
                  </div>
                </div>
              )}
            </div>
          </PrintSection>

          {/* Department-wise Revenue Breakdown */}
          <PrintSection title="Department-wise Revenue Analysis">
            <table className="print-table" style={{ width: '100%', marginBottom: '20pt' }}>
              <thead>
                <tr style={{ backgroundColor: '#f0f0f0' }}>
                  <th style={{
                    width: '10%',
                    textAlign: 'center',
                    padding: '12pt',
                    fontWeight: 'bold',
                    border: '2px solid #000'
                  }}>S.No</th>
                  <th style={{
                    width: '40%',
                    padding: '12pt',
                    fontWeight: 'bold',
                    border: '2px solid #000'
                  }}>Department</th>
                  <th style={{
                    width: '25%',
                    textAlign: 'right',
                    padding: '12pt',
                    fontWeight: 'bold',
                    border: '2px solid #000'
                  }}>Revenue (₹)</th>
                  <th style={{
                    width: '25%',
                    textAlign: 'center',
                    padding: '12pt',
                    fontWeight: 'bold',
                    border: '2px solid #000'
                  }}>Share (%)</th>
                </tr>
              </thead>
              <tbody>
                {departments.map((dept, index) => (
                  <tr key={index}>
                    <td style={{
                      textAlign: 'center',
                      padding: '10pt',
                      border: '1px solid #666'
                    }}>{index + 1}</td>
                    <td style={{
                      padding: '10pt',
                      border: '1px solid #666',
                      fontWeight: 'bold'
                    }}>{dept.department}</td>
                    <td style={{
                      textAlign: 'right',
                      padding: '10pt',
                      border: '1px solid #666',
                      fontFamily: 'monospace'
                    }}>{formatCurrency(dept.revenue)}</td>
                    <td style={{
                      textAlign: 'center',
                      padding: '10pt',
                      border: '1px solid #666',
                      fontWeight: 'bold'
                    }}>{dept.percentage.toFixed(1)}%</td>
                  </tr>
                ))}
                <tr style={{
                  backgroundColor: '#e9ecef',
                  fontWeight: 'bold',
                  fontSize: '14pt'
                }}>
                  <td colSpan={2} style={{
                    textAlign: 'center',
                    padding: '15pt',
                    border: '2px solid #000'
                  }}>
                    <strong>TOTAL</strong>
                  </td>
                  <td style={{
                    textAlign: 'right',
                    padding: '15pt',
                    border: '2px solid #000',
                    fontFamily: 'monospace'
                  }}>
                    <strong>{formatCurrency(totalRevenue)}</strong>
                  </td>
                  <td style={{
                    textAlign: 'center',
                    padding: '15pt',
                    border: '2px solid #000'
                  }}>
                    <strong>100.0%</strong>
                  </td>
                </tr>
              </tbody>
            </table>
          </PrintSection>

          {/* Payment Methods Analysis */}
          <PrintSection title="Payment Methods Analysis">
            <table className="print-table" style={{ width: '100%', marginBottom: '20pt' }}>
              <thead>
                <tr style={{ backgroundColor: '#f0f0f0' }}>
                  <th style={{
                    width: '15%',
                    textAlign: 'center',
                    padding: '12pt',
                    border: '2px solid #000'
                  }}>S.No</th>
                  <th style={{
                    width: '25%',
                    padding: '12pt',
                    border: '2px solid #000'
                  }}>Payment Method</th>
                  <th style={{
                    width: '20%',
                    textAlign: 'center',
                    padding: '12pt',
                    border: '2px solid #000'
                  }}>Transactions</th>
                  <th style={{
                    width: '25%',
                    textAlign: 'right',
                    padding: '12pt',
                    border: '2px solid #000'
                  }}>Amount (₹)</th>
                  <th style={{
                    width: '15%',
                    textAlign: 'right',
                    padding: '12pt',
                    border: '2px solid #000'
                  }}>Avg (₹)</th>
                </tr>
              </thead>
              <tbody>
                {paymentMethods.map((method, index) => (
                  <tr key={index}>
                    <td style={{
                      textAlign: 'center',
                      padding: '10pt',
                      border: '1px solid #666'
                    }}>{index + 1}</td>
                    <td style={{
                      padding: '10pt',
                      border: '1px solid #666',
                      fontWeight: 'bold'
                    }}>{method.method}</td>
                    <td style={{
                      textAlign: 'center',
                      padding: '10pt',
                      border: '1px solid #666'
                    }}>{method.count}</td>
                    <td style={{
                      textAlign: 'right',
                      padding: '10pt',
                      border: '1px solid #666',
                      fontFamily: 'monospace'
                    }}>{formatCurrency(method.amount)}</td>
                    <td style={{
                      textAlign: 'right',
                      padding: '10pt',
                      border: '1px solid #666',
                      fontFamily: 'monospace',
                      fontSize: '10pt'
                    }}>{formatCurrency(method.amount / method.count)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </PrintSection>

          {/* Key Performance Metrics */}
          <PrintSection title="Key Performance Indicators">
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(2, 1fr)',
              gap: '20pt',
              marginBottom: '20pt'
            }}>
              <div style={{
                padding: '15pt',
                border: '2px solid #6c757d',
                textAlign: 'center',
                backgroundColor: '#f8f9fa'
              }}>
                <div style={{ fontSize: '14pt', fontWeight: 'bold', marginBottom: '8pt' }}>
                  Average Daily Revenue
                </div>
                <div style={{ fontSize: '18pt', color: '#28a745', fontWeight: 'bold' }}>
                  {formatCurrency(totalRevenue / 30)} {/* Assuming 30 days */}
                </div>
              </div>

              <div style={{
                padding: '15pt',
                border: '2px solid #6c757d',
                textAlign: 'center',
                backgroundColor: '#f8f9fa'
              }}>
                <div style={{ fontSize: '14pt', fontWeight: 'bold', marginBottom: '8pt' }}>
                  Total Transactions
                </div>
                <div style={{ fontSize: '18pt', color: '#007bff', fontWeight: 'bold' }}>
                  {paymentMethods.reduce((sum, method) => sum + method.count, 0)}
                </div>
              </div>

              <div style={{
                padding: '15pt',
                border: '2px solid #6c757d',
                textAlign: 'center',
                backgroundColor: '#f8f9fa'
              }}>
                <div style={{ fontSize: '14pt', fontWeight: 'bold', marginBottom: '8pt' }}>
                  Average Transaction
                </div>
                <div style={{ fontSize: '18pt', color: '#6f42c1', fontWeight: 'bold' }}>
                  {formatCurrency(totalRevenue / paymentMethods.reduce((sum, method) => sum + method.count, 0))}
                </div>
              </div>

              <div style={{
                padding: '15pt',
                border: '2px solid #6c757d',
                textAlign: 'center',
                backgroundColor: '#f8f9fa'
              }}>
                <div style={{ fontSize: '14pt', fontWeight: 'bold', marginBottom: '8pt' }}>
                  Growth Rate
                </div>
                <div style={{ fontSize: '18pt', color: '#28a745', fontWeight: 'bold' }}>
                  +12.5%
                </div>
              </div>
            </div>
          </PrintSection>

          {/* Revenue Distribution Chart (Text representation) */}
          <PrintSection title="Revenue Distribution Overview">
            <div style={{
              padding: '20pt',
              border: '1px solid #000',
              backgroundColor: '#f9f9f9',
              marginBottom: '20pt'
            }}>
              <h4 style={{
                fontSize: '14pt',
                fontWeight: 'bold',
                marginBottom: '15pt',
                textAlign: 'center',
                textTransform: 'uppercase'
              }}>
                Department Revenue Share
              </h4>
              {departments.map((dept, index) => (
                <div key={index} style={{
                  marginBottom: '12pt',
                  display: 'flex',
                  alignItems: 'center'
                }}>
                  <div style={{ width: '150pt', fontWeight: 'bold' }}>
                    {dept.department}:
                  </div>
                  <div style={{ width: '80pt', textAlign: 'right', marginRight: '10pt' }}>
                    {dept.percentage.toFixed(1)}%
                  </div>
                  <div style={{
                    color: '#28a745',
                    fontSize: '14pt',
                    fontFamily: 'monospace'
                  }}>
                    {'█'.repeat(Math.round(dept.percentage / 2))}
                  </div>
                </div>
              ))}
            </div>
          </PrintSection>

          {/* Notes Section */}
          {revenue.notes && (
            <PrintSection title="Analysis Notes">
              <div style={{
                padding: '15pt',
                border: '1px solid #ccc',
                backgroundColor: '#fafafa',
                fontStyle: 'italic'
              }}>
                {revenue.notes}
              </div>
            </PrintSection>
          )}

          {/* Financial Disclaimer */}
          <div style={{
            marginTop: '30pt',
            padding: '15pt',
            border: '2px solid #dc3545',
            backgroundColor: '#fff5f5'
          }}>
            <h4 style={{
              fontSize: '12pt',
              fontWeight: 'bold',
              marginBottom: '10pt',
              color: '#dc3545',
              textAlign: 'center'
            }}>
              FINANCIAL REPORTING DISCLAIMER
            </h4>
            <ul style={{ fontSize: '11pt', lineHeight: '1.4', paddingLeft: '20pt' }}>
              <li>All figures are exclusive of applicable taxes unless specified</li>
              <li>Revenue data verified against accounting records and bank statements</li>
              <li>Report generated for internal management use only</li>
              <li>Any discrepancies should be reported to finance department immediately</li>
            </ul>
          </div>

          {/* Authorization Signatures */}
          <div className="print-signature-section">
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              marginTop: '50pt',
              pageBreakInside: 'avoid'
            }}>
              <div style={{ width: '200pt', textAlign: 'center' }}>
                <div style={{ height: '40pt' }}></div>
                <div style={{ borderTop: '2px solid #000', paddingTop: '8pt' }}>
                  <strong>Finance Manager</strong>
                </div>
                <div style={{ fontSize: '10pt', marginTop: '5pt' }}>Financial Analysis & Reporting</div>
                <div style={{ fontSize: '10pt' }}>Date: {formatDate(new Date().toISOString())}</div>
              </div>

              <div style={{ width: '200pt', textAlign: 'center' }}>
                <div style={{ height: '40pt' }}></div>
                <div style={{ borderTop: '2px solid #000', paddingTop: '8pt' }}>
                  <strong>Chief Executive Officer</strong>
                </div>
                <div style={{ fontSize: '10pt', marginTop: '5pt' }}>Executive Approval</div>
                <div style={{ fontSize: '10pt' }}>Date: {formatDate(new Date().toISOString())}</div>
              </div>
            </div>
          </div>

          {/* Report Footer */}
          <div style={{
            marginTop: '40pt',
            padding: '15pt',
            border: '2px solid #000',
            backgroundColor: '#e9ecef',
            pageBreakInside: 'avoid'
          }}>
            <div style={{ fontSize: '12pt', textAlign: 'center', fontWeight: 'bold' }}>
              <strong>CONFIDENTIAL FINANCIAL REPORT</strong><br />
              <div style={{ marginTop: '8pt', fontSize: '10pt' }}>
                Report ID: {revenue.id} | Period: {revenue.report_period || 'Current Period'} | Total Revenue: {formatCurrency(totalRevenue)}<br />
                This document contains confidential financial information. Handle according to company data protection policies.
              </div>
            </div>
          </div>
        </PrintLayout>
      </DialogContent>
    </Dialog>
  )
}