"use client"

import * as React from "react"
import { PrintLayout, PrintSection, PrintRow, PrintCol, PrintField, PrintSignature } from "./print-layout"
import { Dialog, DialogContent, DialogTrigger } from "@/components/ui/dialog"

interface RevenuePrintProps {
  revenue: {
    id: string
    report_period: string
    date_from: string
    date_to: string
    total_revenue: number
    total_expenses?: number
    net_profit?: number
    department_breakdown?: Array<{
      department: string
      revenue: number
      percentage: number
    }>
    payment_methods?: Array<{
      method: string
      amount: number
      count: number
    }>
    services_breakdown?: Array<{
      service: string
      count: number
      revenue: number
    }>
    notes?: string
    generated_by?: string
  }
  children: React.ReactNode
}

export function RevenuePrint({ revenue, children }: RevenuePrintProps) {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    })
  }

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      minimumFractionDigits: 2
    }).format(amount)
  }

  // Sample data if none provided
  const defaultDepartments = [
    { department: 'Consultation', revenue: 150000, percentage: 45 },
    { department: 'Surgery', revenue: 100000, percentage: 30 },
    { department: 'Pharmacy', revenue: 50000, percentage: 15 },
    { department: 'Diagnostics', revenue: 33333, percentage: 10 }
  ]

  const defaultPaymentMethods = [
    { method: 'Cash', amount: 200000, count: 150 },
    { method: 'Card', amount: 100000, count: 75 },
    { method: 'UPI', amount: 33333, count: 50 }
  ]

  const departments = revenue.department_breakdown || defaultDepartments
  const paymentMethods = revenue.payment_methods || defaultPaymentMethods
  const totalRevenue = revenue.total_revenue || departments.reduce((sum, dept) => sum + dept.revenue, 0)

  return (
    <Dialog>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <PrintLayout
          documentType="Financial Report"
          documentTitle="Financial Analysis Report"
        >
          <div className="print-financial-report">
            {/* Report Header Information */}
            <PrintSection title="Report Information">
              <PrintRow>
                <PrintCol>
                  <PrintField label="Report Period" value={revenue.report_period || 'CURRENT PERIOD'} />
                  <PrintField label="Date Range" value={`${formatDate(revenue.date_from)} to ${formatDate(revenue.date_to)}`} />
                </PrintCol>
                <PrintCol>
                  <PrintField label="Generated On" value={formatDate(new Date().toISOString())} />
                  <PrintField label="Generated By" value={revenue.generated_by || 'Finance Department'} />
                </PrintCol>
              </PrintRow>
            </PrintSection>

            {/* Executive Summary - Key Metrics Table */}
            <div className="print-executive-summary">
              <div style={{ fontSize: '12pt', fontWeight: 'bold', marginBottom: '10pt', textTransform: 'uppercase' }}>
                Executive Summary
              </div>
              <table>
                <tbody>
                  <tr>
                    <td>
                      <div className="print-metric-label">Total Revenue</div>
                    </td>
                    <td>
                      <div className="print-metric-value">{formatCurrency(totalRevenue)}</div>
                    </td>
                  </tr>
                  {revenue.total_expenses && (
                    <tr>
                      <td>
                        <div className="print-metric-label">Total Expenses</div>
                      </td>
                      <td>
                        <div className="print-metric-value">{formatCurrency(revenue.total_expenses)}</div>
                      </td>
                    </tr>
                  )}
                  {revenue.net_profit !== undefined && (
                    <tr>
                      <td>
                        <div className="print-metric-label">Net Profit/Loss</div>
                      </td>
                      <td>
                        <div className="print-metric-value" style={{ 
                          color: revenue.net_profit >= 0 ? '#000' : '#cc0000' 
                        }}>
                          {formatCurrency(revenue.net_profit)}
                        </div>
                      </td>
                    </tr>
                  )}
                  {revenue.total_expenses && revenue.net_profit !== undefined && (
                    <tr>
                      <td>
                        <div className="print-metric-label">Profit Margin</div>
                      </td>
                      <td>
                        <div className="print-metric-value">
                          {((revenue.net_profit / totalRevenue) * 100).toFixed(2)}%
                        </div>
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>

            {/* Department-wise Revenue Breakdown */}
            <PrintSection title="Department-wise Revenue Breakdown">
              <table className="print-table">
                <thead>
                  <tr>
                    <th style={{ width: '8%', textAlign: 'center' }}>S.No</th>
                    <th style={{ width: '42%' }}>Department</th>
                    <th style={{ width: '30%', textAlign: 'right' }}>Revenue (₹)</th>
                    <th style={{ width: '20%', textAlign: 'center' }}>Share</th>
                  </tr>
                </thead>
                <tbody>
                  {departments.map((dept, index) => (
                    <tr key={index}>
                      <td style={{ textAlign: 'center' }}>{index + 1}</td>
                      <td>{dept.department}</td>
                      <td style={{ textAlign: 'right' }}>{formatCurrency(dept.revenue)}</td>
                      <td style={{ textAlign: 'center' }}>
                        <span className="print-percentage-badge">{dept.percentage.toFixed(1)}%</span>
                      </td>
                    </tr>
                  ))}
                  <tr style={{ fontWeight: 'bold', borderTop: '2px solid #000' }}>
                    <td colSpan={2} style={{ textAlign: 'right', padding: '8pt' }}>
                      <strong>TOTAL</strong>
                    </td>
                    <td style={{ textAlign: 'right', padding: '8pt' }}>
                      <strong>{formatCurrency(totalRevenue)}</strong>
                    </td>
                    <td style={{ textAlign: 'center', padding: '8pt' }}>
                      <strong>100.0%</strong>
                    </td>
                  </tr>
                </tbody>
              </table>
            </PrintSection>

            {/* Payment Methods Analysis */}
            <PrintSection title="Payment Methods Analysis">
              <table className="print-table">
                <thead>
                  <tr>
                    <th style={{ width: '10%', textAlign: 'center' }}>S.No</th>
                    <th style={{ width: '35%' }}>Payment Method</th>
                    <th style={{ width: '20%', textAlign: 'center' }}>Transactions</th>
                    <th style={{ width: '35%', textAlign: 'right' }}>Amount (₹)</th>
                  </tr>
                </thead>
                <tbody>
                  {paymentMethods.map((method, index) => {
                    const percentage = (method.amount / totalRevenue) * 100
                    return (
                      <tr key={index}>
                        <td style={{ textAlign: 'center' }}>{index + 1}</td>
                        <td>{method.method}</td>
                        <td style={{ textAlign: 'center' }}>{method.count}</td>
                        <td style={{ textAlign: 'right' }}>
                          {formatCurrency(method.amount)}
                          <span className="print-percentage-badge" style={{ marginLeft: '8pt' }}>
                            {percentage.toFixed(1)}%
                          </span>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </PrintSection>

            {/* Service Breakdown - If Available */}
            {revenue.services_breakdown && revenue.services_breakdown.length > 0 && (
              <PrintSection title="Service-wise Revenue Breakdown">
                <table className="print-table">
                  <thead>
                    <tr>
                      <th style={{ width: '10%', textAlign: 'center' }}>S.No</th>
                      <th style={{ width: '50%' }}>Service</th>
                      <th style={{ width: '15%', textAlign: 'center' }}>Count</th>
                      <th style={{ width: '25%', textAlign: 'right' }}>Revenue (₹)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {revenue.services_breakdown.map((service, index) => (
                      <tr key={index}>
                        <td style={{ textAlign: 'center' }}>{index + 1}</td>
                        <td>{service.service}</td>
                        <td style={{ textAlign: 'center' }}>{service.count}</td>
                        <td style={{ textAlign: 'right' }}>{formatCurrency(service.revenue)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </PrintSection>
            )}

            {/* Notes Section */}
            {revenue.notes && (
              <PrintSection title="Analysis Notes">
                <div style={{ fontSize: '11pt', lineHeight: '1.5', textAlign: 'justify' }}>
                  {revenue.notes}
                </div>
              </PrintSection>
            )}

            {/* Finance Signature */}
            <PrintSignature 
              doctorName="Finance Manager"
              qualification="Financial Analysis & Reporting"
              registrationNumber=""
              date={formatDate(new Date().toISOString())}
            />
          </div>
        </PrintLayout>
      </DialogContent>
    </Dialog>
  )
}